### ISSUE TITLE
Hi pls help me

### ISSUE THREAD

**Issue by vtnplus** [CryptoManiac/open-ethereum-pool-pps#1]
#### System information

Geth version: `geth version` or commit hash if `develop`

Redis version: `redis-server --version`

OS & Version: Linux/OSX

Commit branch and hash: (`master`, `ba60e1c`)

#### Backtrace

````
[backtrace]
````
i run with parity and get error when found block
panic: interface conversion: redis.Cmder is *redis.StatusCmd, not *redis.StringStringMapCmd

goroutine 89598 [running]:
panic(0x8e3260, 0xc820019a40)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/sammy007/open-ethereum-pool/storage.(*RedisClient).WriteBlock(0xc8200c3da0, 0xc82053d320, 0x2a, 0xc820983a28, 0x4, 0xc8207e9840, 0x3, 0x4, 0x77359400, 0x23d047a27a0e, ...)
        /opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/storage/redis.go:220 +0xb55
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).processShare(0xc820106120, 0xc82053d320, 0x2a, 0xc820983a28, 0x4, 0xc8202e9300, 0xd, 0xc82023aaf0, 0xc8207e9840, 0x3, ...)
        /opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/miner.go:57 +0xbfd
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).handleSubmitRPC(0xc820106120, 0xc820991c00, 0xc82053d320, 0x2a, 0xc820983a28, 0x4, 0xc8207e9840, 0x3, 0x4, 0x804040, ...)
        /opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/handlers.go:72 +0x4d7
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).handleTCPSubmitRPC(0xc820106120, 0xc820991c00, 0xc820983a28, 0x4, 0xc8207e9840, 0x3, 0x4, 0xe9, 0x0)
        /opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/handlers.go:53 +0x145
github.com/sammy007/open-ethereum-pool/proxy.(*Session).handleTCPMessage(0xc820991c00, 0xc820106120, 0xc820558d80, 0x0, 0x0)
        /opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:131 +0x56a
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).handleTCPClient(0xc820106120, 0xc820991c00, 0x0, 0x0)
        /opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:94 +0x8cc
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).ListenTCP.func1(0xc8206afee0, 0xc820106120, 0xc820126dd8, 0xc820150000, 0xc820991c00)
        /opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:55 +0x2f
created by github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).ListenTCP
        /opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:61 +0x6d9

**Comment by CryptoManiac** [comment]
Thanks. Issue seems to be resolved. --Отправлено из мобильной Яндекс.Почты24.09.2017, 23:40, "LARAVELCMS" <notifications@github.com>:System information
Geth version: geth version or commit hash if develop
Redis version: redis-server --version
OS & Version: Linux/OSX
Commit branch and hash: (master, ba60e1c)
Expected behaviour
Actual behaviour
Steps to reproduce the behaviour
Backtrace
[backtrace]

i run with parity and get error when found block
panic: interface conversion: redis.Cmder is *redis.StatusCmd, not *redis.StringStringMapCmd
goroutine 89598 [running]:
panic(0x8e3260, 0xc820019a40)
/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/sammy007/open-ethereum-pool/storage.(*RedisClient).WriteBlock(0xc8200c3da0, 0xc82053d320, 0x2a, 0xc820983a28, 0x4, 0xc8207e9840, 0x3, 0x4, 0x77359400, 0x23d047a27a0e, ...)
/opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/storage/redis.go:220 +0xb55
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).processShare(0xc820106120, 0xc82053d320, 0x2a, 0xc820983a28, 0x4, 0xc8202e9300, 0xd, 0xc82023aaf0, 0xc8207e9840, 0x3, ...)
/opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/miner.go:57 +0xbfd
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).handleSubmitRPC(0xc820106120, 0xc820991c00, 0xc82053d320, 0x2a, 0xc820983a28, 0x4, 0xc8207e9840, 0x3, 0x4, 0x804040, ...)
/opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/handlers.go:72 +0x4d7
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).handleTCPSubmitRPC(0xc820106120, 0xc820991c00, 0xc820983a28, 0x4, 0xc8207e9840, 0x3, 0x4, 0xe9, 0x0)
/opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/handlers.go:53 +0x145
github.com/sammy007/open-ethereum-pool/proxy.(*Session).handleTCPMessage(0xc820991c00, 0xc820106120, 0xc820558d80, 0x0, 0x0)
/opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:131 +0x56a
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).handleTCPClient(0xc820106120, 0xc820991c00, 0x0, 0x0)
/opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:94 +0x8cc
github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).ListenTCP.func1(0xc8206afee0, 0xc820106120, 0xc820126dd8, 0xc820150000, 0xc820991c00)
/opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:55 +0x2f
created by github.com/sammy007/open-ethereum-pool/proxy.(*ProxyServer).ListenTCP
/opt/open-ethereum-pool-pps/build/_workspace/src/github.com/sammy007/open-ethereum-pool/proxy/stratum.go:61 +0x6d9

**Comment by vtnplus** [comment]
thanks is work.
next when payout. 
Unable to process payouts: Your account is locked. Unlock the account via CLI, personal_unlockAccount or use Trusted Signer.
account is unlock. ( test payout with prop work ok )
what is fix it

**Comment by vtnplus** [comment]
thanks you help

**Comment by vtnplus** [comment]
Error with tabs payments. After payment Amout is 0.00000. not update

**Comment by CryptoManiac** [comment]
https://github.com/CryptoManiac/open-ethereum-pool-pps/commit/052d0fceef102025e374d5e5f38db328b6119f85
